"""Golden determinism gate tests — tasks 3.6, 3.7, 3.8 (APPROVAL-PHASE3
Unit 4).

The determinism machinery of Phase 3: the committed golden corpus under
``tests/golden/`` (implementation-generated → ``EVIDENCE_INTEGRITY =
DEGRADED`` by design Determinism Mechanism #6), golden drift detection
(determinism-rendering spec, Golden regression detection), the
``EVIDENCE_INTEGRITY = VALID | DEGRADED | INVALID`` vocabulary, and the
cross-run SHA-256 gate (task 3.8 / Mechanism #5: fresh-interpreter
subprocess compiles under ``python -I`` and ``PYTHONHASHSEED=0`` vs
random → digests equal AND equal to the committed golden digest).

The golden documents are GENERATED by the real chain (feed bytes →
parse → validate → normalize → admit → select → render → lint) over
committed fixture-set inputs — never hand-written. The independent
expected sample under ``tests/golden/independent/`` is NOT this unit's:
it is authored only by the decision owner or an owner-designated audit
path (Unit 5 authored it; ratification flag P3-F10). The sample is
PRESENT and the machinery classifies the real corpus as VALID
(verified corpus + self-consistent independent sample — design #6);
the DEGRADED pending-owner arm stays exercised against a tmp corpus
with the sample removed. Whether the sample's bytes AGREE with the
implementation goldens is the task-3.9 gate computation
(``outputs/phase3-close.md`` Unit B), not this classification arm.

``python -I`` interaction note (empirically pinned on this toolchain):
``-I`` implies ``-E``, which ignores ``PYTHON*`` environment variables,
so ``PYTHONHASHSEED=0 python -I`` is a no-op seed (each isolated run
rolls a fresh random seed). The cross-run gate therefore combines
isolated ``python -I`` runs (random seeds across fresh interpreters)
with non-isolated seeded runs (``PYTHONHASHSEED=0`` vs unset/random) —
the union covers both axes of Mechanism #5.
"""

import hashlib
import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path
from types import ModuleType
from typing import Final

import pytest

pytestmark = pytest.mark.integration

GOLDEN_ROOT: Final[Path] = (
    Path(__file__).resolve().parents[1] / "golden"
)
"""Root of the committed golden corpus (manifest + scenarios)."""

_MACHINERY_PATH: Final[Path] = GOLDEN_ROOT / "golden_machinery.py"
"""The stdlib-only golden machinery module (also the subprocess CLI)."""

_MANIFEST_PATH: Final[Path] = GOLDEN_ROOT / "manifest.json"

SCENARIO_NAMES: Final[tuple[str, ...]] = (
    "pc1_unassessed_fc",
    "pc2_assessed_absence_ta",
    "standard_mixed",
)
"""The frozen golden scenarios: PC-1, PC-2, and the standard set."""

_INDEPENDENT_MANIFEST_RELPATH: Final[str] = "independent/MANIFEST.json"


def _load_machinery() -> ModuleType:
    """Load ``golden_machinery.py`` by file path (no sys.path games).

    The module is stdlib-only at import time (clinical_compiler imports
    are lazy inside its chain composer), so loading it under pytest is
    side-effect free.
    """
    spec = importlib.util.spec_from_file_location(
        "golden_machinery", _MACHINERY_PATH
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def machinery() -> ModuleType:
    """The golden machinery module, loaded once for this test module."""
    return _load_machinery()


def _committed_manifest() -> dict[str, object]:
    """Load the committed golden manifest (must exist and parse)."""
    assert _MANIFEST_PATH.is_file(), (
        "tests/golden/manifest.json is missing — the golden corpus has "
        "not been generated/committed (task 3.7)"
    )
    return json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))


def _scenarios(manifest: dict[str, object]) -> list[dict[str, object]]:
    """The manifest's scenario entries as a list of dicts."""
    scenarios = manifest.get("scenarios")
    assert isinstance(scenarios, list)
    return [entry for entry in scenarios if isinstance(entry, dict)]


def _manifest_digests(machinery: ModuleType) -> dict[str, str]:
    """Committed golden digests per scenario name, from the manifest."""
    return {
        str(entry["name"]): str(entry["sha256"])
        for entry in _scenarios(_committed_manifest())
    }


# --- 1. Golden corpus: committed digests match the committed bytes -------


def test_manifest_records_every_scenario_with_valid_digests(
    machinery: ModuleType,
) -> None:
    """Manifest carries all frozen scenarios; digests are real SHA-256.

    Task 3.7: the golden document AND its SHA-256 digest are committed.
    For every scenario the digest recorded in the manifest must equal
    the SHA-256 of the committed document bytes (and the input digest
    must equal the committed input bytes) — a manifest disagreeing with
    the files it describes is corrupted evidence.
    """
    manifest = _committed_manifest()
    assert manifest["schema"] == "clinical-compiler-r1/golden-manifest/1"
    entries = _scenarios(manifest)
    assert tuple(str(entry["name"]) for entry in entries) == SCENARIO_NAMES

    for entry in entries:
        digest = str(entry["sha256"])
        assert len(digest) == 64
        assert all(char in "0123456789abcdef" for char in digest)

        document_path = GOLDEN_ROOT / str(entry["document"])
        input_path = GOLDEN_ROOT / str(entry["input"])
        assert document_path.is_file(), f"missing golden {document_path}"
        assert input_path.is_file(), f"missing fixture {input_path}"

        document_digest = machinery.sha256_hex(
            document_path.read_bytes()
        )
        assert document_digest == digest, (
            f"scenario {entry['name']}: manifest digest does not match "
            "the committed document bytes"
        )
        assert (
            machinery.sha256_hex(input_path.read_bytes())
            == entry["input_sha256"]
        )


@pytest.mark.parametrize("scenario", SCENARIO_NAMES)
def test_golden_documents_recompile_byte_identical(
    machinery: ModuleType, scenario: str
) -> None:
    """Recompiling the committed fixture set reproduces the golden
    bytes exactly, and the golden document is lint-clean.

    Determinism-rendering spec (Golden digest match): a compile of the
    fixture set must SHA-256 to the committed golden digest; any
    mismatch is drift and blocks. The compile runs the REAL full chain
    through the machinery's composer — the goldens were generated by
    that same composition, never hand-written.
    """
    manifest_entry = next(
        entry
        for entry in _scenarios(_committed_manifest())
        if str(entry["name"]) == scenario
    )
    input_path = GOLDEN_ROOT / str(manifest_entry["input"])
    document_path = GOLDEN_ROOT / str(manifest_entry["document"])

    compiled = machinery.compile_feed(input_path.read_bytes())
    committed = document_path.read_bytes()
    assert compiled == committed
    assert machinery.sha256_hex(compiled) == str(manifest_entry["sha256"])

    linted = machinery.lint_clean(compiled)
    assert linted, "committed golden document must be lint-clean"


# --- 2. Frozen glyph vocabulary (task 3.7 freeze + task 3.6 PC-1 chain) --


def test_glyph_vocabulary_frozen_by_the_golden_corpus() -> None:
    """The first golden files freeze the glyph vocabulary (design Open
    Question 4): every glyph family appears with its exact line bytes.

    Task 3.6 at chain level (PC-1): no fact for ``FC`` renders the
    explicit ``FC: unknown [not_assessed]`` — never dropped, never
    rewritten as assessed absence. PC-2: assessed absence renders
    ``missing`` WITH provenance (traced to a source assertion). The
    standard set pins the numeric glyphs (``str(int)`` /
    ``str(float)``) and the verbatim string glyph.
    """
    def document_lines(scenario: str) -> list[str]:
        entry = next(
            e
            for e in _scenarios(_committed_manifest())
            if str(e["name"]) == scenario
        )
        raw = (GOLDEN_ROOT / str(entry["document"])).read_bytes()
        return raw.decode("utf-8").split("\n")[:-1]

    assert document_lines("pc1_unassessed_fc") == [
        "FC: unknown [not_assessed]",
        "TA: 120/80 [present] [monitor m-9]",
    ]
    assert document_lines("pc2_assessed_absence_ta") == [
        "FC: 72 [present] [monitor m-9]",
        "TA: missing [missing] [clinical_note n-1]",
    ]
    assert document_lines("standard_mixed") == [
        "FC: 80.5 [present] [monitor m-3]",
        "TA: 120/80 [present] [monitor m-9]",
    ]


# --- 3. Golden drift detection (spec: Golden regression detection) ------


def _corpus_copy(tmp_path: Path) -> Path:
    """Copy the committed corpus to tmp for mutation experiments."""
    root = tmp_path / "golden"
    shutil.copytree(GOLDEN_ROOT, root)
    return root


def test_mutated_golden_byte_is_detected_as_drift(
    machinery: ModuleType, tmp_path: Path
) -> None:
    """Flipping one byte of a committed golden document must be caught
    by the machinery (digest mismatch → INVALID evidence).
    """
    root = _corpus_copy(tmp_path)
    document_path = root / "scenarios/pc2_assessed_absence_ta.document.txt"
    mutated = document_path.read_bytes().replace(b"72", b"73")
    assert mutated != document_path.read_bytes()
    document_path.write_bytes(mutated)

    assessment = machinery.assess_golden_evidence(root)
    assert assessment.overall_integrity is machinery.EvidenceIntegrity.INVALID
    assert assessment.phase3_gate_blocked is True


def test_tampered_manifest_digest_is_detected(
    machinery: ModuleType, tmp_path: Path
) -> None:
    """A manifest digest edited independently of its document file is
    corrupted evidence → INVALID.
    """
    root = _corpus_copy(tmp_path)
    manifest_path = root / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["scenarios"][0]["sha256"] = "0" * 64
    manifest_path.write_text(
        json.dumps(manifest, sort_keys=True, indent=2), encoding="utf-8"
    )

    assessment = machinery.assess_golden_evidence(root)
    assert assessment.overall_integrity is machinery.EvidenceIntegrity.INVALID


def test_output_affecting_input_change_breaks_the_golden_comparison(
    machinery: ModuleType,
) -> None:
    """Spec scenario (Golden regression detection): an output-affecting
    change — here a mutated clinical value in the fixture input — makes
    the compile digest differ from the committed golden digest, so at
    least one golden comparison fails.
    """
    entry = next(
        e
        for e in _scenarios(_committed_manifest())
        if str(e["name"]) == "pc2_assessed_absence_ta"
    )
    input_path = GOLDEN_ROOT / str(entry["input"])
    mutated = input_path.read_bytes().replace(b'"raw_value": 72', b'"raw_value": 73')
    assert mutated != input_path.read_bytes()

    drifted_digest = machinery.sha256_hex(machinery.compile_feed(mutated))
    assert drifted_digest != str(entry["sha256"])


# --- 4. EVIDENCE_INTEGRITY vocabulary (design Mechanism #6) --------------


def test_evidence_integrity_vocabulary_is_valid_degraded_invalid(
    machinery: ModuleType,
) -> None:
    """The vocabulary is exactly VALID | DEGRADED | INVALID (M7.1)."""
    values = {member.value for member in machinery.EvidenceIntegrity}
    assert values == {"VALID", "DEGRADED", "INVALID"}
    manifest = _committed_manifest()
    assert set(manifest["evidence_integrity_vocabulary"]) == values


def test_implementation_generated_goldens_are_labeled_degraded(
    machinery: ModuleType,
) -> None:
    """Design #6: implementation-generated goldens are DEGRADED
    evidence by definition — the implementation must not mark its own
    exam VALID.
    """
    for entry in _scenarios(_committed_manifest()):
        assert entry["evidence_integrity"] == "DEGRADED", (
            f"scenario {entry['name']}: implementation-generated golden "
            "must carry EVIDENCE_INTEGRITY=DEGRADED"
        )


def test_independent_sample_presence_upgrades_evidence_to_valid(
    machinery: ModuleType, tmp_path: Path
) -> None:
    """Design #6 / task 3.7: the independently authored sample under
    ``tests/golden/independent/`` is PRESENT (owner-designated
    independent path, Unit 5) and self-consistent, so the machinery
    classifies the real corpus evidence as VALID and Mechanism #6 no
    longer blocks on absence; with the sample removed from a tmp copy
    of the corpus the same machinery must still detect the DEGRADED
    pending-owner state. (Updated from the pending-condition absence
    test once the sample arrived — the update its own failure message
    prescribed.)
    """
    assert (GOLDEN_ROOT / _INDEPENDENT_MANIFEST_RELPATH).is_file(), (
        "the independent sample is absent — golden evidence is DEGRADED "
        "and the Phase 3 determinism gate BLOCKS pending owner input "
        "(design Mechanism #6)"
    )

    assessment = machinery.assess_golden_evidence(GOLDEN_ROOT)
    assert assessment.independent_sample_present is True
    assert assessment.overall_integrity is machinery.EvidenceIntegrity.VALID
    assert assessment.phase3_gate_blocked is False

    absent_root = _corpus_copy(tmp_path)
    shutil.rmtree(absent_root / "independent")
    absent = machinery.assess_golden_evidence(absent_root)
    assert absent.independent_sample_present is False
    assert absent.overall_integrity is machinery.EvidenceIntegrity.DEGRADED
    assert absent.phase3_gate_blocked is True
    assert "owner" in absent.reason


def _install_independent_sample(
    root: Path, *, consistent: bool
) -> None:
    """Simulate an owner-authored independent sample under a tmp corpus.

    Test-local data only (never under the real
    ``tests/golden/independent/``) — it exercises the classification
    machinery's VALID / INVALID arms without authoring the real
    sample. Any ``independent/`` directory that ``_corpus_copy``
    carried over from the real corpus is REMOVED first so the
    simulation is fully isolated from the real sample; the manifest
    mirrors the committed multi-scenario shape (paths relative to the
    corpus root), targeting the standard_mixed fixture set.
    """
    document = (
        b"FC: 80.5 [present] [monitor m-3]\n"
        b"TA: 120/80 [present] [monitor m-9]\n"
    )
    digest = (
        hashlib.sha256(document).hexdigest() if consistent else "0" * 64
    )
    input_path = root / "scenarios/standard_mixed.input.jsonl"
    sample_dir = root / "independent"
    if sample_dir.exists():
        shutil.rmtree(sample_dir)
    sample_dir.mkdir()
    (sample_dir / "standard_mixed.expected.txt").write_bytes(document)
    (sample_dir / "MANIFEST.json").write_text(
        json.dumps(
            {
                "schema": "clinical-compiler-r1/independent-sample/1",
                "author": "decision owner (simulated for machinery test)",
                "scenarios": [
                    {
                        "name": "standard_mixed",
                        "input": "scenarios/standard_mixed.input.jsonl",
                        "input_sha256": hashlib.sha256(
                            input_path.read_bytes()
                        ).hexdigest(),
                        "document": "independent/standard_mixed.expected.txt",
                        "sha256": digest,
                    }
                ],
            },
            sort_keys=True,
            indent=2,
        ),
        encoding="utf-8",
    )


def test_present_independent_sample_upgrades_evidence_to_valid(
    machinery: ModuleType, tmp_path: Path
) -> None:
    """With a self-consistent independent sample present, the golden
    evidence is VALID and the Phase 3 gate is not blocked by #6.
    """
    root = _corpus_copy(tmp_path)
    _install_independent_sample(root, consistent=True)

    assessment = machinery.assess_golden_evidence(root)
    assert assessment.independent_sample_present is True
    assert assessment.overall_integrity is machinery.EvidenceIntegrity.VALID
    assert assessment.phase3_gate_blocked is False


def test_self_inconsistent_independent_sample_is_invalid(
    machinery: ModuleType, tmp_path: Path
) -> None:
    """An independent sample whose recorded digest does not match its
    own document bytes is corrupted evidence → INVALID.
    """
    root = _corpus_copy(tmp_path)
    _install_independent_sample(root, consistent=False)

    assessment = machinery.assess_golden_evidence(root)
    assert assessment.independent_sample_present is True
    assert assessment.overall_integrity is machinery.EvidenceIntegrity.INVALID
    assert assessment.phase3_gate_blocked is True


# --- 5. Cross-run SHA-256 determinism gate (task 3.8) ---------------------


def _child_digest(
    input_path: Path, *, isolated: bool, env: dict[str, str], cwd: Path
) -> str:
    """Compile one fixture set in a FRESH interpreter, return the
    SHA-256 hex of the produced document.

    The child runs the machinery CLI (``digest <input>``) with a
    minimal environment. Isolated runs use ``python -I`` (implies
    ``-E``/``-P``: no PYTHON* env, no user site, no path prepend —
    each run rolls a fresh random hash seed); seeded runs drop ``-I``
    so ``PYTHONHASHSEED`` takes effect.
    """
    argv = [
        sys.executable,
        *(["-I"] if isolated else []),
        str(_MACHINERY_PATH),
        "digest",
        str(input_path),
    ]
    completed = subprocess.run(
        argv,
        capture_output=True,
        check=True,
        timeout=60,
        env=env,
        cwd=cwd,
    )
    return completed.stdout.decode("utf-8").strip()


@pytest.mark.slow
@pytest.mark.parametrize("scenario", SCENARIO_NAMES)
def test_cross_run_digests_equal_and_match_committed_golden(
    machinery: ModuleType, tmp_path: Path, scenario: str
) -> None:
    """Task 3.8 / Mechanism #5: compile the fixture set in fresh
    interpreters under varied conditions — ``python -I`` twice (fresh
    random hash seeds per run), ``PYTHONHASHSEED=0`` (deterministic
    seed), and unset seed (random) — all digests are equal AND equal to
    the committed golden digest (cross-run equality + golden
    regression detection in one gate).
    """
    entry = next(
        e
        for e in _scenarios(_committed_manifest())
        if str(e["name"]) == scenario
    )
    input_path = GOLDEN_ROOT / str(entry["input"])

    digests = [
        _child_digest(
            input_path, isolated=True, env={}, cwd=tmp_path
        ),
        _child_digest(
            input_path, isolated=True, env={}, cwd=tmp_path
        ),
        _child_digest(
            input_path,
            isolated=False,
            env={"PYTHONHASHSEED": "0"},
            cwd=tmp_path,
        ),
        _child_digest(
            input_path, isolated=False, env={}, cwd=tmp_path
        ),
    ]

    assert len(set(digests)) == 1, (
        f"cross-run digest divergence for {scenario}: {digests}"
    )
    assert digests[0] == str(entry["sha256"]), (
        f"cross-run digest for {scenario} does not match the committed "
        "golden digest (golden regression detected)"
    )
